version: '3'
services:
  web:
    labels:
      - "traefik.http.routers.web.rule=Host(`sentry.makedeb.org`)"
      - "traefik.enable=true"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"
